# Generated by Django 3.2.25 on 2026-01-06 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_collectors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collected_amount',
            field=models.FloatField(default=0),
        ),
    ]
