# Generated by Django 3.2.25 on 2026-01-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_collectionitem_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('duration_days', models.IntegerField(default=30, help_text='Duration in days (e.g., 30 for monthly, 365 for yearly)')),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='is_trial_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subscriptionplan'),
        ),
    ]
