# Generated by Django 3.2.25 on 2026-01-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionItem',
        ),
    ]
