# Generated by Django 3.2.25 on 2026-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260106_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectors',
            name='can_collect_directly',
            field=models.BooleanField(default=False),
        ),
    ]
