# Generated by Django 3.2.25 on 2026-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_collection_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
