# Generated by Django 6.0.1 on 2026-02-17 11:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashs',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='cashs',
            name='party_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collected_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='godown_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='open_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='open_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='open_debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='otc_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='otc_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='customers',
            name='otc_debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='open_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='open_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='open_debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='otc_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='otc_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='otc_debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='receiver_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sell_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sell_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sender_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchaser_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='seller_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='sales',
            name='purchaser_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='sales',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='stocktransfers',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='open_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='open_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='open_debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='otc_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='otc_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='otc_debit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
    ]
