# Generated by Django 5.2.7 on 2026-02-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_companydetail_supportcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportcontact',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
        migrations.DeleteModel(
            name='SupportContact',
        ),
    ]
