# Generated by Django 5.2.7 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_supportcontact_company_delete_companydetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
