# Generated by Django 5.2.7 on 2026-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_useraccount_last_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
