# Generated by Django 5.2.10 on 2026-03-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_adminexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexpense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexpense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
