# Generated by Django 5.2.10 on 2026-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_adminexpense_deleted_at_adminexpense_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
