# Generated by Django 5.2.7 on 2026-03-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_clients_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='has_whatsapp_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='whatsapp_client_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='whatsapp_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='whatsapp_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('linked', 'Linked')], db_index=True, default='inactive', max_length=20),
        ),
    ]
