# Generated by Django 5.2.7 on 2026-03-04 12:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_adminexpense_amount_alter_cashs_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godowns',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
    ]
