# Generated by Django 5.2.7 on 2026-03-04 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_godowns_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbanks',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AddField(
            model_name='cashs',
            name='cash_bank_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
    ]
