# Generated by Django 5.2.7 on 2026-03-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cashbanks_balance_cashs_cash_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashs',
            name='cash_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.cashbanks'),
        ),
        migrations.AlterField(
            model_name='cashs',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.customers'),
        ),
        migrations.AlterField(
            model_name='cashs',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.suppliers'),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.expenses'),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.godowns'),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='receiver_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receiver_customer', to='core.customers'),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='receiver_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receiver_supplier', to='core.suppliers'),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sender_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sender_customer', to='core.customers'),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sender_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sender_supplier', to='core.suppliers'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.customers'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.godowns'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.suppliers'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.customers'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.godowns'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.suppliers'),
        ),
    ]
