# Generated by Django 6.0.2 on 2026-03-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_cashs_cash_bank_alter_cashs_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.godowns'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliers'),
        ),
    ]
