# Generated by Django 5.2.7 on 2026-03-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_purchases_customer_alter_purchases_godown_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
