# Generated by Django 5.2.10 on 2026-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_collectionitem_options_collectionitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
