# Generated by Django 5.2.7 on 2026-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_clients_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbanks',
            name='cashbankId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectors',
            name='collectorId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expenseId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='godownId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplierId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cashbanks',
            unique_together={('client', 'cashbankId')},
        ),
        migrations.AlterUniqueTogether(
            name='collectors',
            unique_together={('client', 'collectorId')},
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('client', 'customerId')},
        ),
        migrations.AlterUniqueTogether(
            name='expenses',
            unique_together={('client', 'expenseId')},
        ),
        migrations.AlterUniqueTogether(
            name='godowns',
            unique_together={('client', 'godownId')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliers',
            unique_together={('client', 'supplierId')},
        ),
    ]
