# Generated by Django 5.2.7 on 2026-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_cashbanks_cashbankid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashs',
            index=models.Index(fields=['client', 'is_active', 'date'], name='core_cashs_client__f477c2_idx'),
        ),
        migrations.AddIndex(
            model_name='commissions',
            index=models.Index(fields=['client', 'is_active', 'date'], name='core_commis_client__9372be_idx'),
        ),
        migrations.AddIndex(
            model_name='purchases',
            index=models.Index(fields=['client', 'is_active', 'date'], name='core_purcha_client__bdacc7_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['client', 'is_active', 'date'], name='core_sales_client__2c77b2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfers',
            index=models.Index(fields=['client', 'is_active', 'date'], name='core_stockt_client__b4b557_idx'),
        ),
    ]
