# Generated by Django 5.2.7 on 2026-03-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cashs_core_cashs_client__f477c2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='clientId',
        ),
        migrations.AddField(
            model_name='clients',
            name='commission_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashs',
            name='cash_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='commission_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='nsd_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfers',
            name='transfer_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cashs',
            unique_together={('client', 'cash_no')},
        ),
        migrations.AlterUniqueTogether(
            name='commissions',
            unique_together={('client', 'commission_no')},
        ),
        migrations.AlterUniqueTogether(
            name='nsds',
            unique_together={('client', 'nsd_no')},
        ),
        migrations.AlterUniqueTogether(
            name='purchases',
            unique_together={('client', 'purchase_no')},
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('client', 'sale_no')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktransfers',
            unique_together={('client', 'transfer_no')},
        ),
        migrations.AddIndex(
            model_name='nsds',
            index=models.Index(fields=['client', 'is_active', 'date'], name='core_nsds_client__df3a1f_idx'),
        ),
    ]
