# Generated by Django 5.2.7 on 2026-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_clients_clientid_clients_commission_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='commission_no',
        ),
        migrations.AddField(
            model_name='clients',
            name='clientId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
