# Generated by Django 5.2.7 on 2026-03-10 20:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_clients_commission_no_clients_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cashs',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='open_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='open_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='otc_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='otc_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='open_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='open_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='otc_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='otc_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nsds',
            name='sell_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stocktransfers',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='open_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='open_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='otc_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='otc_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='adminexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='adminexpense_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cashs',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='cashs_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='collection_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='collectionitem_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.CheckConstraint(condition=models.Q(('collected_amount__gte', Decimal('0.00'))), name='collectionitem_collected_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissions',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', Decimal('0.00'))), name='commissions_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissions',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='commissions_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissions',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='commissions_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('open_credit__gte', Decimal('0.00'))), name='customers_open_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('open_debit__gte', Decimal('0.00'))), name='customers_open_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('otc_credit__gte', Decimal('0.00'))), name='customers_otc_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('otc_debit__gte', Decimal('0.00'))), name='customers_otc_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', Decimal('0.00'))), name='customers_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', Decimal('0.00'))), name='customers_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expenses',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='expenses_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('open_credit__gte', Decimal('0.00'))), name='godowns_open_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('open_debit__gte', Decimal('0.00'))), name='godowns_open_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('otc_credit__gte', Decimal('0.00'))), name='godowns_otc_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('otc_debit__gte', Decimal('0.00'))), name='godowns_otc_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', Decimal('0.00'))), name='godowns_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', Decimal('0.00'))), name='godowns_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='godowns',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', Decimal('0.00'))), name='godowns_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='nsds',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', Decimal('0.00'))), name='nsds_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='nsds',
            constraint=models.CheckConstraint(condition=models.Q(('sell_rate__gte', Decimal('0.00'))), name='nsds_sell_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='nsds',
            constraint=models.CheckConstraint(condition=models.Q(('sell_amount__gte', Decimal('0.00'))), name='nsds_sell_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='nsds',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_rate__gte', Decimal('0.00'))), name='nsds_purchase_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='nsds',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_amount__gte', Decimal('0.00'))), name='nsds_purchase_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', Decimal('0.00'))), name='purchases_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='purchases_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='purchases_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', Decimal('0.00'))), name='sales_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='sales_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='sales_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfers',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', Decimal('0.00'))), name='stocktransfers_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='subscriptionpayment_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='subscriptionplan_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliers',
            constraint=models.CheckConstraint(condition=models.Q(('open_credit__gte', Decimal('0.00'))), name='suppliers_open_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliers',
            constraint=models.CheckConstraint(condition=models.Q(('open_debit__gte', Decimal('0.00'))), name='suppliers_open_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliers',
            constraint=models.CheckConstraint(condition=models.Q(('otc_credit__gte', Decimal('0.00'))), name='suppliers_otc_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliers',
            constraint=models.CheckConstraint(condition=models.Q(('otc_debit__gte', Decimal('0.00'))), name='suppliers_otc_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliers',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', Decimal('0.00'))), name='suppliers_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliers',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', Decimal('0.00'))), name='suppliers_debit_gte_0'),
        ),
    ]
