# Generated by Django 5.2.7 on 2026-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_adminexpense_amount_alter_cashs_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='clientId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
