# Generated by Django 5.2.7 on 2026-03-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_security_audit_low_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='wa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
