# Generated by Django 5.2.7 on 2026-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_security_audit_high_fixes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['client', 'is_active'], name='idx_customers_client_active'),
        ),
        migrations.AddIndex(
            model_name='suppliers',
            index=models.Index(fields=['client', 'is_active'], name='idx_suppliers_client_active'),
        ),
    ]
