# Generated by Django 5.2.7 on 2026-03-11 23:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_customers_idx_customers_client_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='godowns',
            name='godowns_qty_gte_0',
        ),
        migrations.AlterField(
            model_name='godowns',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
    ]
