# Generated by Django 5.2.10 on 2026-03-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_expenses_date_alter_purchases_customer_and_more'),
        ('core', '0040_remove_godowns_godowns_qty_gte_0_alter_godowns_qty'),
    ]

    operations = [
    ]
