# Generated by Django 5.2.10 on 2026-03-13 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20260313_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfers',
            name='transfer_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
