# Generated by Django 3.2.25 on 2025-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='godowns',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
