# Generated by Django 3.2.25 on 2025-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251124_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashs',
            name='party_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commissions',
            name='godown_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nsds',
            name='receiver_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nsds',
            name='sender_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='purchaser_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='seller_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='purchaser_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='seller_balance',
            field=models.FloatField(default=0),
        ),
    ]
