# Generated by Django 5.2.7 on 2025-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
