# Generated by Django 3.2.25 on 2025-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251124_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='godowns',
            name='open_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='godowns',
            name='otc_balance',
            field=models.FloatField(default=0),
        ),
    ]
