# Generated by Django 5.2.7 on 2025-10-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expenses_amount_expenses_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('godownId', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_credit', models.FloatField(default=0)),
                ('open_debit', models.FloatField(default=0)),
                ('otc_credit', models.FloatField(default=0)),
                ('otc_debit', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
