# Generated by Django 5.2.7 on 2025-12-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20251206_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hold', models.BooleanField(default=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients')),
                ('transfer_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='core.godowns')),
                ('transfer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='core.godowns')),
            ],
        ),
    ]
