# Generated by Django 5.2.7 on 2025-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_collectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectors',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectors',
            name='wa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='wa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='wa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='wa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
