# Generated by Django 3.2.25 on 2026-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_collectors_can_collect_directly'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
