# Generated by Django 5.2.7 on 2025-10-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.godowns'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='purchase_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliers'),
        ),
    ]
