# Generated by Django 5.2.7 on 2025-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purchases_amount_purchases_code_purchases_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
