# Generated by Django 5.2.7 on 2025-10-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_purchases_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='rate',
        ),
    ]
