# Generated by Django 5.2.7 on 2025-10-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_purchases_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='customers',
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.godowns')),
            ],
        ),
    ]
