# Generated by Django 5.2.7 on 2025-10-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_purchases_customers_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_no', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.expenses')),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.godowns')),
            ],
        ),
        migrations.CreateModel(
            name='NSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsd_no', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(default=0)),
                ('sell_rate', models.FloatField(default=0)),
                ('purchase_rate', models.FloatField(default=0)),
                ('sell_amount', models.FloatField(default=0)),
                ('purchase_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliers')),
            ],
        ),
    ]
