# Generated by Django 5.2.7 on 2025-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_commission_nsd'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
