# Generated by Django 5.2.7 on 2025-10-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_purchases_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers'),
        ),
    ]
