# Generated by Django 5.2.7 on 2025-10-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_purchases_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
