# Generated by Django 5.2.7 on 2025-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_purchases_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='godowns',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
