# Generated by Django 5.2.7 on 2025-10-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customers_balance_godowns_balance_suppliers_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='customers',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='sales',
            name='hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliers'),
        ),
        migrations.AddField(
            model_name='sales',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
