# Generated by Django 5.2.7 on 2025-10-30 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_nsds_delete_nsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsds',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='nsds',
            name='supplier',
        ),
        migrations.AddField(
            model_name='nsds',
            name='receiver_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_customer', to='core.customers'),
        ),
        migrations.AddField(
            model_name='nsds',
            name='receiver_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_supplier', to='core.suppliers'),
        ),
        migrations.AddField(
            model_name='nsds',
            name='sender_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_customer', to='core.customers'),
        ),
        migrations.AddField(
            model_name='nsds',
            name='sender_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_supplier', to='core.suppliers'),
        ),
        migrations.CreateModel(
            name='Cashs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsd_no', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(default=0)),
                ('sell_rate', models.FloatField(default=0)),
                ('sell_amount', models.FloatField(default=0)),
                ('purchase_rate', models.FloatField(default=0)),
                ('purchase_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hold', models.BooleanField(default=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('cashbank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashbanks')),
            ],
        ),
    ]
