# Generated by Django 5.2.7 on 2025-11-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_nsds_customer_remove_nsds_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashs',
            old_name='purchase_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='cashs',
            old_name='cashbank',
            new_name='cash_bank',
        ),
        migrations.RenameField(
            model_name='cashs',
            old_name='code',
            new_name='cash_no',
        ),
        migrations.RemoveField(
            model_name='cashs',
            name='purchase_rate',
        ),
        migrations.RemoveField(
            model_name='cashs',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='cashs',
            name='sell_amount',
        ),
        migrations.RemoveField(
            model_name='cashs',
            name='sell_rate',
        ),
        migrations.RemoveField(
            model_name='cashs',
            name='type',
        ),
        migrations.AddField(
            model_name='cashs',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers'),
        ),
        migrations.AddField(
            model_name='cashs',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliers'),
        ),
    ]
