# Generated by Django 5.2.7 on 2025-11-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_purchase_amount_cashs_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashs',
            name='nsd_no',
        ),
    ]
