# Generated by Django 3.2.25 on 2025-11-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_cashs_nsd_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashs',
            name='transaction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
