# Generated by Django 5.2.7 on 2025-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_collector',
            field=models.BooleanField(default=False),
        ),
    ]
