# Generated by Django 5.2.7 on 2025-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_clients_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
