# Generated by Django 5.2.7 on 2025-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_clients_country_code_clients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='wa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
