# Generated by Django 5.2.7 on 2025-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_clients_wa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='clientId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
