# Generated by Django 3.2.25 on 2025-11-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_clients_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbanks',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='cashs',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='collectors',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='commissions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='customers',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='godowns',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='nsds',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
    ]
