# Generated by Django 5.2.7 on 2025-11-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20251113_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='debit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='debit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='debit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
