# Generated by Django 5.2.7 on 2025-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_customers_credit_customers_debit_godowns_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customers',
            name='debit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='debit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='debit',
            field=models.FloatField(default=0),
        ),
    ]
